services:
  - type: web
    name: poi-backend
    env: python
    buildCommand: "cd backend && pip install torch --index-url https://download.pytorch.org/whl/cpu && pip install -r requirements.txt"
    startCommand: "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
    plan: starter # Recommendation for RAM requirements
