[project]
name = "backend"
version = "0.1.0"
description = "Optimized POI Backend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "better-profanity>=0.7.0",
    "fastapi>=0.128.5",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "pillow>=11.3.0",
    "python-multipart>=0.0.22",
    "qdrant_client>=1.16.2",
    "sentence-transformers>=3.3.0",
    "torch>=2.5.0",
    "uvicorn>=0.40.0",
]
